spring:
  datasource:
    url : jdbc:h2:tcp://localhost/~/selfmadeboard
    username : sa
    password:
    driver-class-name : org.h2.Driver


  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  jpa:
    hibernate:
      ddl-auto: create
