spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/selfmadeboard
    username : sa
    password :
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      open-in-view: false
      hibernate:
        format_sql: true


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace